"""Migration test 1

Revision ID: 42982162b562
Revises: 
Create Date: 2020-05-13 16:24:55.664583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42982162b562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
